version: '3'
services:
  db:
    container_name: test-db
    image: mysql:5.7.12
    ports:
      - 13306:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - ./mysql:/var/lib/mysql
  web:
    container_name: test-web
    build:
      context: __web__
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - $SRC_WEB:/app:cached
    depends_on:
      - db
  vue_web:
    container_name: test-vue
    build:
      context: __vue__
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    entrypoint: sh
    command: -c "yarn install && yarn run serve"
    ports:
      - 8081:8080
    volumes:
      - $SRC_WEB:/app:cached
    stdin_open: true
    tty: true
